name: Java CI with Maven

on:
  push:
    branches:
      - master # Run on pushes to the main branch
  pull_request:
    branches:
      - master # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22' # Set to Java 22
          distribution: 'temurin' # Use Eclipse Temurin JDK
          cache: maven # Cache Maven dependencies

      # Step 3: Install dependencies and run tests
      - name: Run tests with Maven
        run: mvn clean test

      # Step 4: Archive test results (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/ # Path where Maven stores test results
