name: Java CI with JUnit

on:
  push:
    branches:
      - master  # Run on pushes to the main branch
  pull_request:
    branches:
      - master  # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22' # Specify the Java version (e.g., 8, 11, 17)

      # Step 3: Install dependencies and build
      - name: Build with Gradle
        run: ./mvn test # For Gradle users
        # Use 'mvn test' for Maven users

      # Step 4: Run tests
      - name: Run JUnit Tests
        run: ./mvn test # For Gradle users
        # Use 'mvn test' for Maven users

      # Step 5: Publish test results (optional)
      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test  # Path to test reports
